package com.xplete.lingoz.database;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;

import com.xplete.lingoz.models.LemmaModel;
import com.xplete.lingoz.models.LocaleModel;
import com.xplete.lingoz.models.TranslationModel;
import com.xplete.lingoz.provider.LingozContract;

public class LingozDbInit {
    public static void initDb(SQLiteDatabase db) {
        initLemmas(db);
        initTranslations(db);
        initLocales(db);
    }

    private static void initTranslations(SQLiteDatabase db) {
        initDbBulkInsert(db, LingozContract.TranslationEntry.TABLE_NAME, Translations.getContentValues(translations));
    }

    private static void initLocales(SQLiteDatabase db) {
        initDbBulkInsert(db, LingozContract.LocaleEntry.TABLE_NAME, Locales.getContentValues(locales));
    }

    private static void initLemmas(SQLiteDatabase db) {
        initDbBulkInsert(db, LingozContract.LemmaEntry.TABLE_NAME, Lemmas.getContentValues(lemmas));
    }

    private static void initDbBulkInsert(SQLiteDatabase db, String tableName, ContentValues[] valuesArray) {
        db.beginTransaction();
        try {
            for (ContentValues values : valuesArray) {
                db.insertWithOnConflict(tableName, null, values, SQLiteDatabase.CONFLICT_REPLACE);
                //db.yieldIfContendedSafely(); // temporarily releases the transaction so the UI is not blocked
            }
            db.setTransactionSuccessful();
        } finally {
            db.endTransaction();
        }
    }

    private static final LemmaModel[] lemmas = {
            new LemmaModel(1, "abrasion", 1, "(medical) an injury caused by scraping or grazing the skin", "She suffered only minor abrasions in the accident."),
            new LemmaModel(2, "accord", 2, "(with) (formal) to agree with", "His story accords with what I saw happen."),
            new LemmaModel(3, "ad", 1, "(informal) short for advertisement", "I'll put an ad in the newspaper."),
            new LemmaModel(4, "adult", 3, "fully grown", "an adult gorilla."),
            new LemmaModel(5, "afield", 7, "far or further away", "Trips further afield can be made by car."),
            new LemmaModel(6, "ail", 2, "(old-fashioned) to be ill", "The old lady has been ailing for some time."),
            new LemmaModel(7, "allegory", 1, "a story, poem, or picture in which the events and characters represent different qualities or ideas", "The novel is an allegory about American society and            politics in the 1890s."),
            new LemmaModel(8, "aluminium", 1, "a light, silver-coloured metal used in making saucepans etc. It is a chemical element and has the symbol Al", "pans made of aluminium"),
            new LemmaModel(9, "amokəˈmok", 1, "to rush about madly, attacking everybody and everything", "The prisoner ran amok and killed two prison officers."),
            new LemmaModel(10, "antagonist", 1, "an opponent or enemy", "His next antagonist in the competition is the current            world champion."),
            new LemmaModel(11, "apathy", 1, "a lack of interest or enthusiasm", "his apathy towards his work."),
            new LemmaModel(12, "artificial", 3, "made by man; not natural; not real", "artificial flowers"),
            new LemmaModel(13, "asset", 1, "anything useful or valuable; an advantage", "He is a great asset to the school."),
            new LemmaModel(14, "attend", 2, "(formal) to go to or be present at", "She attended the meeting"),
            new LemmaModel(15, "bale", 2, "(alsobail) to clear (water out of a boat with buckets etc)", "Several gallons of water were baled out of the boat."),
            new LemmaModel(16, "bar", 1, "a rod or oblong piece (especially of a solid substance)", "a gold bar"),
            new LemmaModel(17, "bass", 1, "(music) (a singer having) a male voice of the lowest pitch", "He sings in a rich bass."),
            new LemmaModel(18, "bear", 1, "a large heavy animal with thick fur and hooked claws", "a grizzly bear."),
            new LemmaModel(19, "behind", 10, "at or towards the back of", "He hid behind the door."),
            new LemmaModel(20, "beseech", 2, "(literary) to beg", "Don't harm him – I beseech you!"),
            new LemmaModel(21, "bilateral", 3, "affecting, signed, or agreed, by two sides, countries etc", "a bilateral agreement."),
            new LemmaModel(22, "bit", 1, "a small piece", "a bit of cheese."),
            new LemmaModel(23, "blizzard", 1, "a blinding storm of wind and snow", "Two climbers are missing after yesterday's blizzard."),
            new LemmaModel(24, "boggle", 2, "(informal) to be so shocked or surprised by something that you find it difficult to believe or accept", "Her eyes boggled at the amount of money he had in the suitcase."),
            new LemmaModel(25, "bore", 2, "to make (someone) feel tired and uninterested, by being dull etc", "He bores everyone with stories about his travels."),
            new LemmaModel(26, "brook", 1, "a small stream", "a babbling brook."),
            new LemmaModel(27, "bugle", 1, "(music) a musical wind instrument usually made of brass, used chiefly for military signals", "He plays the bugle."),
            new LemmaModel(28, "burger", 1, "a round flat piece of minced beef/ground beef which is cooked and served in a bread bun; hamburger", "She ordered a burger and fries."),
            new LemmaModel(29, "cabaret", 1, "an entertainment given in a restaurant etc", "a singer in a cabaret"),
            new LemmaModel(30, "calypso", 1, "a West Indian folk-song, telling of a current event and sometimes made up as the singer goes along", "(also adjective) a calypso band."),
            new LemmaModel(31, "canopy", 1, "a covering hung over a throne, bed etc or (on poles) as a shelter", "We sheltered under a canvas canopy in front of the            restaurant entrance."),
            new LemmaModel(32, "carcinoma", 1, "(medical) a malignant tumour/tumor", "The surgeons had to remove the carcinoma from his lungs."),
            new LemmaModel(33, "case", 1, "a container or outer covering", "a case of medical instruments"),
            new LemmaModel(34, "cater", 2, "to provide food etc", "They cater for all types of functions including wedding receptions."),
            new LemmaModel(35, "cellar", 1, "a room, especially underground, especially for stores of coal or wine", "a wine cellar."),
            new LemmaModel(36, "chafe", 2, "to make or become sore by rubbing", "These tight shoes chafe my feet."),
            new LemmaModel(37, "charter", 1, "a formal document giving rights or privileges", "the United Nations Charter of Human Rights."),
            new LemmaModel(38, "chicory", 1, "a plant whose leaves are used in salads and whose root is ground and mixed with coffee", "(also adjective) chicory salad."),
            new LemmaModel(39, "chop", 1, "(in plural) (informal) the jaws or mouth, especially of an animal", "The tiger was licking its chops."),
            new LemmaModel(40, "cinch", 1, "(American, informal) a certainty", "He's a cinch to win the title."),
            new LemmaModel(41, "clarity", 1, "the state of being clear or easy to see through", "The water in the lake is remarkable for its clarity."),
            new LemmaModel(42, "coal", 1, "a black mineral burned for fuel, heat etc", "a lump of coal."),
            new LemmaModel(43, "cognitive", 3, "connected with the mental processes of recognizing and understanding things", "cognitive psychology"),
            new LemmaModel(44, "combat", 1, "(an act of) fighting", "The two knights met each other in single combat."),
            new LemmaModel(45, "con", 2, "(informal) to trick or persuade dishonestly", "He conned her into giving him money."),
            new LemmaModel(46, "consent", 2, "to give permission or agree (to)", "I had no choice but to consent to the plan"),
            new LemmaModel(47, "contend", 2, "(usually withwith) to struggle against", "The fishing industry has to contend with several            problems."),
            new LemmaModel(48, "convey", 2, "(formal) to carry", "Huge ships convey oil from the Middle East."),
            new LemmaModel(49, "coroner", 1, "an official who inquires into the causes of accidental or sudden, unexpected deaths", "a coroner's report."),
            new LemmaModel(50, "counsel", 1, "advice", "He'll give you good counsel on your problems."),
            new LemmaModel(51, "croon", 2, "to sing or hum in a low voice", "She crooned a lullaby."),
            new LemmaModel(52, "cub", 1, "the young of certain animals such as foxes, lions etc", "a bear cub."),
            new LemmaModel(53, "cycle", 1, "a number of events happening one after the other in a certain order", "the life-cycle of the butterfly."),
            new LemmaModel(54, "dash", 2, "to move with speed and violence", "A squirrel dashed across the road."),
            new LemmaModel(55, "deception", 1, "(an act of) deceiving", "She was found guilty of attaining the goods by deception."),
            new LemmaModel(56, "deficient", 3, "lacking in what is needed", "Their diet is deficient in certain vitamins."),
            new LemmaModel(57, "demeanour", 1, "manner; bearing; the way one behaves", "Generally her demeanour was thoughtful and            serious."),
            new LemmaModel(58, "depress", 2, "to make sad or gloomy", "I am always depressed by wet weather."),
            new LemmaModel(59, "detain", 2, "to hold back and delay", "I won't detain you – I can see you're in a hurry."),
            new LemmaModel(60, "diarrhoea", 1, "(medical) too much liquid in and too frequent emptying of the bowels", "He has diarrhoea."),
            new LemmaModel(61, "din", 1, "a loud continuous noise", "What a terrible din that machine makes!"),
            new LemmaModel(62, "disclaim", 2, "(formal) to refuse to have anything to do with; to deny", "She disclaimed all responsibility for the accident."),
            new LemmaModel(63, "dishonest", 3, "not honest; deceitful", "dishonest business practices"),
            new LemmaModel(64, "disrepute", 1, "bad reputation", "He has brought the family into disrepute."),
            new LemmaModel(65, "divert", 2, "to cause to turn aside or change direction", "Traffic had to be diverted because of the accident."),
            new LemmaModel(66, "dominant", 3, "ruling; most important; strongest", "the dominant group in society"),
            new LemmaModel(67, "drain", 2, "to clear (land) of water by the use of ditches and pipes", "There are plans to drain the marsh."),
            new LemmaModel(68, "dupe", 1, "a person who is cheated or deceived", "She had been the dupe of a dishonest rogue."),
            new LemmaModel(69, "eel", 1, "a kind of fish with a long smooth cylindrical or ribbon-shaped body", "jellied eels."),
            new LemmaModel(70, "embers", 11, "the sparking or glowing remains of a fire", "I watched the last embers of the fire grow dim."),
            new LemmaModel(71, "enact", 2, "to make into a law or pass a law", "The government intends to enact a new sexual harassment law."),
            new LemmaModel(72, "enmity", 1, "unfriendliness; hatred", "the enmity between the two men"),
            new LemmaModel(73, "enumerate", 2, "(formal) to give a list of", "He enumerated my faults – laziness, vanity etc."),
            new LemmaModel(74, "erect", 3, "upright", "He held his head erect."),
            new LemmaModel(75, "etiquette", 1, "rules for correct or polite behaviour/behavior between people, or within certain professions", "medical/legal etiquette."),
            new LemmaModel(76, "example", 1, "something that represents other things of the same kind; a specimen", "an example of his handwriting."),
            new LemmaModel(77, "extinct", 3, "(of a type of animal etc) no longer in existence", "Mammoths became extinct in prehistoric times."),
            new LemmaModel(78, "faculty", 1, "a power of the mind", "the faculty of reason."),
            new LemmaModel(79, "farm", 1, "an area of land, including buildings, used for growing crops, breeding and keeping cows, sheep, pigs etc", "Much of England is good agricultural land and there are many farms."),
            new LemmaModel(80, "feed", 2, "to give food to", "He fed the child with a spoon."),
            new LemmaModel(81, "filter", 1, "a strainer or other device through which liquid, gas, smoke etc can pass, but not solid material", "A filter is used to make sure that the oil is clean and does not contain any dirt"),
            new LemmaModel(82, "flamboyant", 3, "intended to attract notice", "flamboyant clothes."),
            new LemmaModel(83, "flirt", 2, "(often withwith) to behave (towards someone) as though one were in love but without serious intentions", "She flirts with every man she meets."),
            new LemmaModel(84, "FM", 13, "short for frequency modulation; a system used for broadcasting high-quality radio signals", "(also adjective) an FM radio station."),
            new LemmaModel(85, "forsake", 2, "to leave alone; to abandon", "He was forsaken by his friends."),
            new LemmaModel(86, "frantic", 3, "anxious or very worried", "The frantic mother searched for her child."),
            new LemmaModel(87, "frown", 2, "to make the forehead wrinkle and the eyebrows move down (as a sign of worry, disapproval, deep thought etc)", "He frowned at her bad behaviour."),
            new LemmaModel(88, "fuse", 2, "to melt (together) as a result of great heat", "Copper and tin fuse together to make bronze."),
            new LemmaModel(89, "gawky", 3, "(of a person) looking clumsy or awkward", "She is tall and gawky."),
            new LemmaModel(90, "gentility", 1, "good manners, often to too great an extent", "His gentility impressed Martha's parents."),
            new LemmaModel(91, "gloss", 1, "brightness or shininess on the surface", "Her hair has a lovely gloss"),
            new LemmaModel(92, "gong", 1, "a metal plate which, when struck, gives a ringing sound", "a dinner gong."),
            new LemmaModel(93, "graze", 2, "(of animals) to eat grass etc which is growing", "The cows are grazing in the meadow."),
            new LemmaModel(94, "ground", 1, "the solid surface of the Earth", "She was lying on the ground"),
            new LemmaModel(95, "gulp", 2, "to swallow eagerly or in large mouthfuls", "He gulped down a cup of tea."),
            new LemmaModel(96, "hair", 1, "one of the mass of thread-like objects that grow from the skin", "He brushed the dog's hairs off his jacket."),
            new LemmaModel(97, "harbour", 1, "a place of shelter for ships", "All the ships stayed in (the) harbour/harbor during the storm."),
            new LemmaModel(98, "heir", 1, "a person who by law receives wealth, property etc when the owner dies", "A person's eldest son is usually his heir"),
            new LemmaModel(99, "hip", 1, "(the bones in) either of the two sides of the body just below the waist", "She fell and broke her left hip."),
            new LemmaModel(100, "horror", 1, "great fear or dislike", "She has a horror of spiders"),
            new LemmaModel(101, "humane", 3, "kind; not cruel", "a humane man"),
            new LemmaModel(102, "idiom", 1, "an expression with a meaning that cannot be guessed from the meanings of the individual words", "'To kick the bucket' is an informal idiom meaning 'to die'."),
            new LemmaModel(103, "immense", 3, "very large or very great", "an immense forest"),
            new LemmaModel(104, "implore", 2, "to ask earnestly", "She implored her husband to give up his life of crime"),
            new LemmaModel(105, "inattentive", 3, "not paying attention; not attentive", "This pupil is very inattentive in class"),
            new LemmaModel(106, "inconsiderate", 3, "not showing thought for the feelings, rights etc of other people; thoughtless", "It was inconsiderate of you to arrive without telephoning first."),
            new LemmaModel(107, "indisposed", 3, "(slightly) ill", "The princess is indisposed and has cancelled her engagements."),
            new LemmaModel(108, "infiltrate", 2, "(of soldiers) to get through enemy lines a few at a time", "The troops managed to infiltrate (into) enemy territory."),
            new LemmaModel(109, "ink", 1, "a black or coloured/colored liquid used in writing, printing etc", "Please sign your name in ink rather than pencil"),
            new LemmaModel(110, "insight", 1, "(the quality of having) an understanding of something", "He shows remarkable insight (into children's problems)."),
            new LemmaModel(111, "interval", 1, "a time or space between", "He returned home after an interval of two hours."),
            new LemmaModel(112, "invisible", 3, "not able to be seen", "Only in stories can people make themselves invisible."),
            new LemmaModel(113, "-ish", 12, "(used with adjectives) used to mean quite or slightly", "The room was painted a greenish colour."),
            new LemmaModel(114, "jagged", 3, "having rough or sharp and uneven edges", "a jagged piece of broken glass"),
            new LemmaModel(115, "jibe", 1, "a cruel or unkind remark or taunt", "cruel jibes."),
            new LemmaModel(116, "jug", 1, "a deep container for liquids, usually with a handle and a shaped lip for pouring", "a jug of water"),
            new LemmaModel(117, "karaoke", 1, "a form of entertainment in which people sing the words to popular songs while a machine plays the music", "(also adjective) a karaoke            bar/machine/night."),
            new LemmaModel(118, "kinetic", 3, "of motion", "kinetic energy."),
            new LemmaModel(119, "languish", 2, "to grow weak; to waste away", "He's probably languishing in a jail somewhere."),
            new LemmaModel(120, "ledger", 1, "the book of accounts of an office or shop", "He made an entry in the ledger."),
            new LemmaModel(121, "lilt", 1, "(a tune etc with) a strong rhythm", "The song has a swinging lilt to it."),
            new LemmaModel(122, "lock", 1, "a piece of hair", "She cut off a lock of his hair."),
            new LemmaModel(123, "lounge", 2, "to lie back in a casual manner", "Paula was lounging on a sofa."),
            new LemmaModel(124, "luscious", 3, "very sweet, juicy and delicious", "a luscious peach."),
            new LemmaModel(125, "magnanimous", 3, "(formal) noble and generous", "a magnanimous gesture."),
            new LemmaModel(126, "man", 1, "an adult male human being", "Hundreds of men, women and children"),
            new LemmaModel(127, "marijuana", 1, "a type of drug (illegal in many countries) made from the dried flowers and leaves of the hemp plant", "He was arrested for possession of marijuana."),
            new LemmaModel(128, "meagre", 3, "poor or not enough", "They had to survive on a meagre portion of rice."),
            new LemmaModel(129, "melanin", 1, "(biology) any of various naturally occurring black or dark brown pigments responsible for the colour/color of the skin, hair, and eyes of humans and animals", "Many albinos are sensitive to sunlight and develop sunburn because of the lack of melanin."),
            new LemmaModel(130, "merit", 1, "the quality of worth, excellence or praiseworthiness", "He reached his present position through merit."),
            new LemmaModel(131, "mischief", 1, "action or behaviour (especially of children) that causes small troubles or annoyance to others", "That boy is always up to some mischief."),
            new LemmaModel(132, "morbid", 3, "sick (in the way one shows his/her excessive interest in death, disease, cruel acts etc)", "his morbid fascination with horror films"),
            new LemmaModel(133, "mountain", 1, "a high hill", "Mount Everest is the highest mountain in the world"),
            new LemmaModel(134, "multiply", 2, "to add a number to itself a given number of times and find the total", "4 + 4 + 4 or 4 multiplied by 3 or 4  3 = 12."),
            new LemmaModel(135, "myopia", 1, "(medical) short-sightedness", "She suffers from myopia."),
            new LemmaModel(136, "non-stop", 3, "continuing without a stop", "non-stop entertainment"),
            new LemmaModel(137, "nr", 4, "(British) short for near, used in addresses", "Ponsbourne Park, Nr Hertford."),
            new LemmaModel(138, "obelisk", 1, "a tall pointed stone pillar which has been built in memory of a person or an event", "The obelisk was initially erected by the Pharaoh Rameses II in Heliopolis."),
            new LemmaModel(139, "omnivore", 1, "(biology) an animal or person that eats both meat and plants", "Most birds are omnivores."),
            new LemmaModel(140, "optimize", 2, "to make something as good or effective as it can be", "We’re researching techniques that optimize the use of the world's dwindling energy supply."),
            new LemmaModel(141, "osmosis", 1, "(biology, chemistry) the process of a liquid gradually passing through a membrane", "The water moves up through the plant stem by a process of osmosis."),
            new LemmaModel(142, "outright", 7, "honestly", "I told him outright what I thought."),
            new LemmaModel(143, "overlap", 2, "to extend over and cover a part of", "The pieces of cloth overlapped (each other)."),
            new LemmaModel(144, "paroxysm", 1, "a sudden sharp attack (of pain, rage, laughter etc)", "paroxysms of laughter."),
            new LemmaModel(145, "patent", 1, "an official licence/license from the government giving one person or business the right to make and sell a particular article and to prevent others from doing the same", "She took out a patent on her design"),
            new LemmaModel(146, "permeate", 2, "(of a liquid, gas etc) to pass or spread into or through", "The water had permeated (through/into) the soil."),
            new LemmaModel(147, "phagocyte", 1, "(biology) a type of cell within the body that is able to absorb waste material, bacteria, and other small cells", "Phagocytes absorb invading pathogens."),
            new LemmaModel(148, "physique", 1, "the structure of a person's body", "He has a poor/powerful physique."),
            new LemmaModel(149, "pimple", 1, "a small round swelling on the skin", "He had a pimple on his nose."),
            new LemmaModel(150, "pitter-patter", 1, "a light, tapping sound", "the pitter-patter of rain on the window."),
            new LemmaModel(151, "platinum", 1, "(chemistry) (symbolPt) an element, a heavy, valuable grey/gray metal, often used in making jewellery/jewelry", "(also adjective) a platinum ring."),
            new LemmaModel(152, "porcelain", 1, "(of) a kind of fine china", "That dish is made of porcelain"),
            new LemmaModel(153, "posterior", 3, "coming, or situated behind", "the posterior cruciate ligament"),
            new LemmaModel(154, "PR", 13, "short for public relations", "This campaign is good for the firm's PR."),
            new LemmaModel(155, "pregnant", 3, "carrying unborn young in the womb", "a pregnant woman"),
            new LemmaModel(156, "prevent", 2, "to stop (someone doing something or something happening)", "He prevented me from going."),
            new LemmaModel(157, "probable", 3, "that may be expected to happen or be true; likely", "the probable result"),
            new LemmaModel(158, "prone", 3, "lying flat, especially face downwards", "She was found lying prone on the floor."),
            new LemmaModel(159, "provide", 2, "to give or supply", "He provided the wine for the meal"),
            new LemmaModel(160, "purpose", 1, "the reason for doing something; the aim to which an action etc is directed", "What is the purpose of your visit?"),
            new LemmaModel(161, "quality", 1, "the extent to which something has features which are good or bad etc, especially features which are good", "We produce several different qualities of paper"),
            new LemmaModel(162, "quit", 2, "to leave, stop, or resign from etc", "I'm going to quit teaching"),
            new LemmaModel(163, "rape", 1, "the crime of having sexual intercourse with a woman against her will", "statutory rape"),
            new LemmaModel(164, "re-", 8, "(in some adjectives, adverbs, nouns, and verbs) again", "reheated"),
            new LemmaModel(165, "receptive", 3, "(of people, their minds etc) quick to understand and accept new ideas etc", "He seemed quite receptive to my suggestion."),
            new LemmaModel(166, "recur", 2, "to happen again; to come back again", "This problem keeps recurring."),
            new LemmaModel(167, "refuse", 1, "rubbish; waste material from eg a kitchen", "household refuse."),
            new LemmaModel(168, "relief", 1, "a lessening or stopping of pain, worry, boredom etc", "When you have a headache, an aspirin can bring relief"),
            new LemmaModel(169, "replace", 2, "to put, use etc (a person, thing etc), or to be put, used etc, in place of another", "I must replace that broken lock"),
            new LemmaModel(170, "resource", 1, "(usually in plural) something that gives help, support etc when needed; a supply; a means", "We have used up all our resources"),
            new LemmaModel(171, "reveal", 2, "to make known", "All their secrets have been revealed."),
            new LemmaModel(172, "ribosome", 1, "(biology, chemistry) a small round structure that is found inside a living cell and which consists of proteins and RNA molecules. It is the site where the cell’s proteins are manufactured", "Ribosomes are responsible for the production of proteins."),
            new LemmaModel(173, "road", 1, "a strip of ground usually with a hard level surface for people, vehicles etc to travel on", "This road takes you past the school"),
            new LemmaModel(174, "scandal", 1, "something that is considered shocking or disgraceful", "The price of such food is a scandal."),
            new LemmaModel(175, "scotch", 2, "to put an end to (a rumour/rumor, plan etc)", "They scotched his attempt to become the chairman."),
            new LemmaModel(176, "scuffle", 1, "a confused fight usually between a few people using their fists, feet etc", "The two men quarrelled and there was a scuffle."),
            new LemmaModel(177, "see", 2, "to have the power of sight", "After six years of blindness, he found he could see."),
            new LemmaModel(178, "self-possessed", 3, "calm, and able to act confidently in an emergency", "a calm, self-possessed person."),
            new LemmaModel(179, "sensibility", 1, "an awareness of, or an ability to create, art, literature etc showing very high standards of beauty and good taste", "a writer of great sensibility."),
            new LemmaModel(180, "share", 1, "one of the parts of something that is divided among several people etc", "We all had a share of the cake"),
            new LemmaModel(181, "shirt", 1, "a kind of garment worn on the upper part of the body", "a casual shirt"),
            new LemmaModel(182, "simmer", 2, "to (cause to) cook gently at or just below boiling point", "The stew simmered on the stove"),
            new LemmaModel(183, "skid", 2, "to slide accidentally sideways", "His back wheel skidded and he fell off his bike."),
            new LemmaModel(184, "slew", 2, "to (cause to) turn or swing in a certain direction", "The car skidded and slewed across the road."),
            new LemmaModel(185, "smash", 2, "(sometimes withup) to (cause to) break in pieces or be ruined", "The plate dropped on the floor and smashed into little pieces"),
            new LemmaModel(186, "snore", 2, "to make a noise like a snort while sleeping, when one is breathing in", "He was obviously asleep because he was snoring loudly."),
            new LemmaModel(187, "solemn", 3, "serious and earnest", "a solemn question"),
            new LemmaModel(188, "soup", 1, "a liquid food made from meat, vegetables etc", "She made some chicken soup."),
            new LemmaModel(189, "speckle", 1, "a little spot on a different-coloured background", "The eggs were pale blue with dark green speckles."),
            new LemmaModel(190, "squabble", 2, "to quarrel noisily, usually about something unimportant", "The children are always squabbling over the toys."),
            new LemmaModel(191, "stricken", 3, "deeply affected, overwhelmed or afflicted", "In his youth he was stricken with a crippling disease"),
            new LemmaModel(192, "subsidy", 1, "(a sum of) money paid by a government etc to an industry etc that needs help, or to farmers etc to keep the price of their products low", "farming subsidies."),
            new LemmaModel(193, "supersonic", 3, "faster than the speed of sound", "These planes travel at supersonic speeds."),
            new LemmaModel(194, "swagger", 2, "to walk as though very pleased with oneself", "I saw him swaggering along the street in his new suit."),
            new LemmaModel(195, "sword", 1, "a weapon with a long blade that is sharp on one or both edges", "He drew his sword (from its sheath) and killed the man."),
            new LemmaModel(196, "tactic", 1, "a method or plan for achieving something", "The opposition have accused the government of employing delaying tactics."),
            new LemmaModel(197, "technical", 3, "having, or relating to, a particular science or skill, especially of a mechanical or industrial kind", "a technical college"),
            new LemmaModel(198, "tempt", 2, "to (try to) persuade or attract to do something; to make (someone) want to do (something)", "The sunshine tempted them (to go) out."),
            new LemmaModel(199, "testimony", 1, "the statement(s) made by a person or people who testify in a law-court; evidence", "The jury listened to his testimony."),
            new LemmaModel(200, "thief", 1, "a person who steals", "The thief got away with all my money."),
            new LemmaModel(201, "throng", 1, "a crowd", "Throngs of people gathered to see the Queen."),
            new LemmaModel(202, "tilt", 2, "to go or put (something) into a sloping or slanting position", "He tilted his chair backwards"),
            new LemmaModel(203, "toil", 2, "to work hard and long", "He toiled all day in the fields."),
            new LemmaModel(204, "torment", 1, "(a) very great pain, suffering, worry etc", "He was in torment."),
            new LemmaModel(205, "traffic", 1, "vehicles, aircraft, ships etc moving about", "There's a lot of traffic on the roads / on the river."),
            new LemmaModel(206, "turmoil", 1, "a state of wild confused movement or disorder", "The crowd / His mind was in (a) turmoil."),
            new LemmaModel(207, "type", 1, "(a particular variety of) metal blocks with letters, numbers etc used in printing", "Can we have the headline printed in a different type?"),
            new LemmaModel(208, "unattended", 3, "not under the care or supervision of anybody", "It is dangerous to leave small children unattended in the house."),
            new LemmaModel(209, "undercarriage", 1, "the landing-gear of an aircraft", "The pilot had some difficulty in lowering the undercarriage."),
            new LemmaModel(210, "undress", 2, "to take the clothes off (a person)", "She undressed the child"),
            new LemmaModel(211, "unobtrusive", 3, "not too obvious or noticeable", "She is quiet and unobtrusive."),
            new LemmaModel(212, "unstrap", 2, "to unfasten the strap of", "She unstrapped her suitcase."),
            new LemmaModel(213, "upon", 10, "on", "He sat upon the floor"),
            new LemmaModel(214, "venison", 1, "the flesh of deer, used as food", "We had roast venison for dinner"),
            new LemmaModel(215, "vibrate", 2, "to (cause to) shake, tremble, or move rapidly back and forth", "Every sound that we hear is making part of our ear vibrate"),
            new LemmaModel(216, "visa", 1, "a mark or stamp put on a passport by the authorities of a country to show that the bearer may travel to, or in, that country", "I have applied for a visa for the United States."),
            new LemmaModel(217, "vulgar", 3, "not generally socially acceptable, decent or polite; ill-mannered", "Such behaviour is regarded as vulgar."),
            new LemmaModel(218, "wanton", 3, "without reason; motiveless", "wanton cruelty"),
            new LemmaModel(219, "weary", 3, "tired; with strength or patience exhausted", "a weary sigh"),
            new LemmaModel(220, "when", 7, "at what time(?)", "When did you arrive?"),
            new LemmaModel(221, "whopping", 3, "(informal) (alsowhopping great) huge; very large or big", "a whopping lie"),
            new LemmaModel(222, "winnow", 2, "to separate the chaff from (the grain) by wind", "The newly harvested wheat is being winnowed from the chaff."),
            new LemmaModel(223, "world", 1, "the planet Earth", "every country of the world."),
            new LemmaModel(224, "yesterday", 1, "(on) the day before today", "Yesterday was a tiring day"),
            new LemmaModel(225, "zone", 1, "an area or region, usually of a country, town etc, especially one marked off for a special purpose", "a no-parking zone")
    };


    private static final TranslationModel[] translations = {
            new TranslationModel(1, 10, "abrasion"),
            new TranslationModel(1, 20, "שִׁפשׁוּף"),
            new TranslationModel(1, 30, "ссадина"),
            new TranslationModel(1, 40, "abrasione"),
            new TranslationModel(1, 50, "擦伤"),
            new TranslationModel(2, 10, "s'accorder (avec), concorder (avec)"),
            new TranslationModel(2, 20, "תוֹאֵם אֶת"),
            new TranslationModel(2, 30, "согласовываться"),
            new TranslationModel(2, 40, "concordare con"),
            new TranslationModel(2, 50, "一致"),
            new TranslationModel(3, 10, "annonce"),
            new TranslationModel(3, 20, "מודעה, פרסום, פרסומת"),
            new TranslationModel(3, 30, "реклама; объявление"),
            new TranslationModel(3, 40, "annuncio"),
            new TranslationModel(3, 50, "广告(缩写式)"),
            new TranslationModel(4, 10, "adulte"),
            new TranslationModel(4, 20, "מְבוּגָר"),
            new TranslationModel(4, 30, "взрослый"),
            new TranslationModel(4, 40, "adulto"),
            new TranslationModel(4, 50, "成年人的"),
            new TranslationModel(5, 10, "loin, lointain"),
            new TranslationModel(5, 20, "הרחק"),
            new TranslationModel(5, 30, "вдаль, дальше"),
            new TranslationModel(5, 40, "lontano"),
            new TranslationModel(5, 50, "更远地"),
            new TranslationModel(6, 10, "souffrir"),
            new TranslationModel(6, 20, "לִהיוֹת חוֹלֶה"),
            new TranslationModel(6, 30, "хворать"),
            new TranslationModel(6, 40, "essere sofferente, sentir dolore"),
            new TranslationModel(6, 50, "生病"),
            new TranslationModel(7, 10, "allégorie"),
            new TranslationModel(7, 20, "אלגוריה, משל"),
            new TranslationModel(7, 30, "аллегория"),
            new TranslationModel(7, 40, "allegoria"),
            new TranslationModel(7, 50, "寓言"),
            new TranslationModel(8, 10, "aluminium"),
            new TranslationModel(8, 20, "אָלוּמִיניוּם"),
            new TranslationModel(8, 30, "алюминий; алюминиевый"),
            new TranslationModel(8, 40, "alluminio"),
            new TranslationModel(8, 50, "铝"),
            new TranslationModel(9, 10, "devenir fou furieux, pêter un câble"),
            new TranslationModel(9, 20, "לְהִשׁתוֹלֵל בְטֵרוּף"),
            new TranslationModel(9, 30, "безумствовать"),
            new TranslationModel(9, 40, "diventare pazzo furioso*"),
            new TranslationModel(9, 50, "发狂，到处进攻"),
            new TranslationModel(10, 10, "antagoniste"),
            new TranslationModel(10, 20, "יָרִיב"),
            new TranslationModel(10, 30, "антагонист; противник"),
            new TranslationModel(10, 40, "antagonista"),
            new TranslationModel(10, 50, "对抗者"),
            new TranslationModel(11, 10, "apathie"),
            new TranslationModel(11, 20, "אֲדִישוּת"),
            new TranslationModel(11, 30, "безразличие; апатия"),
            new TranslationModel(11, 40, "apatia"),
            new TranslationModel(11, 50, "冷淡"),
            new TranslationModel(12, 10, "artificiel"),
            new TranslationModel(12, 20, "מְלָאכוּתִי"),
            new TranslationModel(12, 30, "искусственный"),
            new TranslationModel(12, 40, "artificiale"),
            new TranslationModel(12, 50, "人工的"),
            new TranslationModel(13, 10, "atout"),
            new TranslationModel(13, 20, "נֶכֶס"),
            new TranslationModel(13, 30, "ценность"),
            new TranslationModel(13, 40, "vantaggio, bene"),
            new TranslationModel(13, 50, "有价值的人或物，优点"),
            new TranslationModel(14, 10, "assister à, suivre"),
            new TranslationModel(14, 20, "לִהְיוֹת נוֹכַח"),
            new TranslationModel(14, 30, "посещать"),
            new TranslationModel(14, 40, "assistere a, seguire"),
            new TranslationModel(14, 50, "参加"),
            new TranslationModel(15, 10, "écoper"),
            new TranslationModel(15, 20, "לְרוֹקֵן מִמָים"),
            new TranslationModel(15, 30, "вычерпывать (воду)"),
            new TranslationModel(15, 40, "vuotare, gettare in mare*"),
            new TranslationModel(15, 50, "舀水"),
            new TranslationModel(16, 10, "barre, tablette"),
            new TranslationModel(16, 20, "חֲפִיסָה, מוֹט"),
            new TranslationModel(16, 30, "брусок; плитка; прут"),
            new TranslationModel(16, 40, "barra; tavoletta; sbarra"),
            new TranslationModel(16, 50, "条"),
            new TranslationModel(17, 10, "basse"),
            new TranslationModel(17, 20, "בַּס"),
            new TranslationModel(17, 30, "бас"),
            new TranslationModel(17, 40, "basso"),
            new TranslationModel(17, 50, "男低音"),
            new TranslationModel(18, 10, "ours"),
            new TranslationModel(18, 20, "דֹב"),
            new TranslationModel(18, 30, "медведь"),
            new TranslationModel(18, 40, "orso"),
            new TranslationModel(18, 50, "熊"),
            new TranslationModel(19, 10, "derrière"),
            new TranslationModel(19, 20, "מֵאֲחוֹרֵי"),
            new TranslationModel(19, 30, "за, сзади, позади"),
            new TranslationModel(19, 40, "dietro"),
            new TranslationModel(19, 50, "在...之后"),
            new TranslationModel(20, 10, "supplier, implorer"),
            new TranslationModel(20, 20, "לְהַפצִיר, לְהִתחַנֵן"),
            new TranslationModel(20, 30, "умолять"),
            new TranslationModel(20, 40, "supplicare"),
            new TranslationModel(20, 50, "恳求"),
            new TranslationModel(21, 10, "bilatéral"),
            new TranslationModel(21, 20, "דוִ-צְדָדִי"),
            new TranslationModel(21, 30, "двусторонний"),
            new TranslationModel(21, 40, "bilaterale"),
            new TranslationModel(21, 50, "双方的，双边的"),
            new TranslationModel(22, 10, "(petit) morceau"),
            new TranslationModel(22, 20, "חֲתִיכָה, חֶלֶק"),
            new TranslationModel(22, 30, "кусочек"),
            new TranslationModel(22, 40, "morso, boccone"),
            new TranslationModel(22, 50, "少量，少许，小片，小块"),
            new TranslationModel(23, 10, "blizzard"),
            new TranslationModel(23, 20, "סוּפַת שֶׁלֶג"),
            new TranslationModel(23, 30, "буран, вьюга"),
            new TranslationModel(23, 40, "tormenta, tempesta di neve"),
            new TranslationModel(23, 50, "暴风雪，大风雪"),
            new TranslationModel(24, 10, "être stupéfait"),
            new TranslationModel(24, 20, "להיות מופתע"),
            new TranslationModel(24, 30, "пугаться, бояться"),
            new TranslationModel(24, 40, "impressionarsi"),
            new TranslationModel(24, 50, "惊恐"),
            new TranslationModel(25, 10, "ennuyer"),
            new TranslationModel(25, 20, "לְשַעֲמֵם"),
            new TranslationModel(25, 30, "надоедать"),
            new TranslationModel(25, 40, "annoiare"),
            new TranslationModel(25, 50, "使厌烦"),
            new TranslationModel(26, 10, "ruisseau"),
            new TranslationModel(26, 20, "פֶּלֶג"),
            new TranslationModel(26, 30, "ручей"),
            new TranslationModel(26, 40, "ruscello"),
            new TranslationModel(26, 50, "小河"),
            new TranslationModel(27, 10, "clairon"),
            new TranslationModel(27, 20, "חֲצוֹצרָה"),
            new TranslationModel(27, 30, "горн"),
            new TranslationModel(27, 40, "trombetta"),
            new TranslationModel(27, 50, "号角，军号"),
            new TranslationModel(28, 10, "hamburger"),
            new TranslationModel(28, 20, "המבורגר"),
            new TranslationModel(28, 30, "гамбургер"),
            new TranslationModel(28, 40, "burger"),
            new TranslationModel(28, 50, "汉堡包"),
            new TranslationModel(29, 10, "(de) cabaret"),
            new TranslationModel(29, 20, "קַבָּרֶט"),
            new TranslationModel(29, 30, "кабаре"),
            new TranslationModel(29, 40, "cabaret"),
            new TranslationModel(29, 50, "餐馆中的歌舞表演"),
            new TranslationModel(30, 10, "calypso"),
            new TranslationModel(30, 20, "קָלִיפּסוֹ"),
            new TranslationModel(30, 30, "калипсо"),
            new TranslationModel(30, 40, "calipso"),
            new TranslationModel(30, 50, "卡里普索（西印度群岛的民歌，即兴小调）"),
            new TranslationModel(31, 10, "dais, baldaquin"),
            new TranslationModel(31, 20, "חוּפָּה"),
            new TranslationModel(31, 30, "балдахин"),
            new TranslationModel(31, 40, "baldacchino"),
            new TranslationModel(31, 50, "（宝座或床等上面的）华盖，遮篷"),
            new TranslationModel(32, 10, "carcinome"),
            new TranslationModel(32, 20, "גִדוּל מַמאִיר"),
            new TranslationModel(32, 30, "злокачественная опухоль"),
            new TranslationModel(32, 40, "carcinoma"),
            new TranslationModel(32, 50, "恶性瘤"),
            new TranslationModel(33, 10, "boîte, étui, trousse, valise"),
            new TranslationModel(33, 20, "תִּיק"),
            new TranslationModel(33, 30, "сумка; чемодан"),
            new TranslationModel(33, 40, "astuccio, custodia; valigia"),
            new TranslationModel(33, 50, "箱子，外壳"),
            new TranslationModel(34, 10, "fournir des repas"),
            new TranslationModel(34, 20, "לְסֵּפק שֵרוּתֵי הַסעָדָה"),
            new TranslationModel(34, 30, "поставлять провизию"),
            new TranslationModel(34, 40, "provvedere cibi, bevande, ecc."),
            new TranslationModel(34, 50, "供应伙食"),
            new TranslationModel(35, 10, "cave"),
            new TranslationModel(35, 20, "מַרתֵף"),
            new TranslationModel(35, 30, "подвал; погреб"),
            new TranslationModel(35, 40, "cantina"),
            new TranslationModel(35, 50, "地窖"),
            new TranslationModel(36, 10, "irriter"),
            new TranslationModel(36, 20, "לְהַכאִיב מִשִפשוּף"),
            new TranslationModel(36, 30, "натирать"),
            new TranslationModel(36, 40, "irritare"),
            new TranslationModel(36, 50, "擦破"),
            new TranslationModel(37, 10, "charte"),
            new TranslationModel(37, 20, "מְגִילָת זְכוּיוֹת"),
            new TranslationModel(37, 30, "хартия"),
            new TranslationModel(37, 40, "carta, statuto"),
            new TranslationModel(37, 50, "特许状"),
            new TranslationModel(38, 10, "chicorée"),
            new TranslationModel(38, 20, "עוֹלֶש"),
            new TranslationModel(38, 30, "цикорий"),
            new TranslationModel(38, 40, "cicoria"),
            new TranslationModel(38, 50, "菊苣"),
            new TranslationModel(39, 10, "mãchoire(s)"),
            new TranslationModel(39, 20, "לוֹע"),
            new TranslationModel(39, 30, "челюсти"),
            new TranslationModel(39, 40, "mascella"),
            new TranslationModel(39, 50, "颚或嘴"),
            new TranslationModel(40, 10, "certitude"),
            new TranslationModel(40, 20, "דָבַר בָּטוּח"),
            new TranslationModel(40, 30, "верняк"),
            new TranslationModel(40, 40, "certezza"),
            new TranslationModel(40, 50, "必然的事情"),
            new TranslationModel(41, 10, "limpidité"),
            new TranslationModel(41, 20, "בְּהִירוּת"),
            new TranslationModel(41, 30, "прозрачность"),
            new TranslationModel(41, 40, "limpidezza"),
            new TranslationModel(41, 50, "清澈"),
            new TranslationModel(42, 10, "charbon"),
            new TranslationModel(42, 20, "פֶּחָם"),
            new TranslationModel(42, 30, "уголь"),
            new TranslationModel(42, 40, "carbone"),
            new TranslationModel(42, 50, "煤"),
            new TranslationModel(43, 10, "cognitif"),
            new TranslationModel(43, 20, "קוגניטיבי, הכרני"),
            new TranslationModel(43, 30, "когнитивный"),
            new TranslationModel(43, 40, "cognitivo"),
            new TranslationModel(43, 50, "认识(力)的"),
            new TranslationModel(44, 10, "combat"),
            new TranslationModel(44, 20, "קְרָב"),
            new TranslationModel(44, 30, "поединок"),
            new TranslationModel(44, 40, "combattimento, battaglia"),
            new TranslationModel(44, 50, "战斗"),
            new TranslationModel(45, 10, "arnaquer"),
            new TranslationModel(45, 20, "לְרָמוֹת"),
            new TranslationModel(45, 30, "обманом выманивать"),
            new TranslationModel(45, 40, "raggirare, truffare"),
            new TranslationModel(45, 50, "哄骗"),
            new TranslationModel(46, 10, "consentir (à)"),
            new TranslationModel(46, 20, "לְהַסכִּים"),
            new TranslationModel(46, 30, "давать разрешение;соглашаться"),
            new TranslationModel(46, 40, "acconsentire"),
            new TranslationModel(46, 50, "同意"),
            new TranslationModel(47, 10, "lutter (contre)"),
            new TranslationModel(47, 20, "לְהִתמוֹדֵד"),
            new TranslationModel(47, 30, "бороться (с)"),
            new TranslationModel(47, 40, "contendere, combattere"),
            new TranslationModel(47, 50, "搏斗，斗争"),
            new TranslationModel(48, 10, "transporter"),
            new TranslationModel(48, 20, "לְהוֹבִיל"),
            new TranslationModel(48, 30, "перевозить"),
            new TranslationModel(48, 40, "trasportare"),
            new TranslationModel(48, 50, "运送"),
            new TranslationModel(49, 10, "coroner"),
            new TranslationModel(49, 20, "חוֹקֵר מִקרֵי מָווֵת"),
            new TranslationModel(49, 30, "коронер"),
            new TranslationModel(49, 40, "coroner, (magistrato che indaga sui casi di morte violenta o comunque sospetti)"),
            new TranslationModel(49, 50, "验尸官"),
            new TranslationModel(50, 10, "conseil"),
            new TranslationModel(50, 20, "עֵצָה"),
            new TranslationModel(50, 30, "совет"),
            new TranslationModel(50, 40, "consiglio"),
            new TranslationModel(50, 50, "忠告"),
            new TranslationModel(51, 10, "fredonner"),
            new TranslationModel(51, 20, "לְזָמֵר בְּקוֹל רָך"),
            new TranslationModel(51, 30, "напевать вполголоса"),
            new TranslationModel(51, 40, "canticchiare"),
            new TranslationModel(51, 50, "低吟，低声歌唱"),
            new TranslationModel(52, 10, "petit (d'un animal)"),
            new TranslationModel(52, 20, "גוּר"),
            new TranslationModel(52, 30, "детёныш"),
            new TranslationModel(52, 40, "cucciolo (di certi animali selvatici)"),
            new TranslationModel(52, 50, "幼兽"),
            new TranslationModel(53, 10, "cycle"),
            new TranslationModel(53, 20, "מַחֲזוֹר"),
            new TranslationModel(53, 30, "цикл"),
            new TranslationModel(53, 40, "ciclo"),
            new TranslationModel(53, 50, "周期，循环"),
            new TranslationModel(54, 10, "se précipiter"),
            new TranslationModel(54, 20, "לְזַנֵק"),
            new TranslationModel(54, 30, "броситься"),
            new TranslationModel(54, 40, "balzare"),
            new TranslationModel(54, 50, "猛冲"),
            new TranslationModel(55, 10, "tromperie"),
            new TranslationModel(55, 20, "מִרמָה, הוֹנָאָה"),
            new TranslationModel(55, 30, "обман"),
            new TranslationModel(55, 40, "inganno"),
            new TranslationModel(55, 50, "欺骗"),
            new TranslationModel(56, 10, "défectueux, insuffisant"),
            new TranslationModel(56, 20, "חָסֵר"),
            new TranslationModel(56, 30, "недостаточный"),
            new TranslationModel(56, 40, "carente"),
            new TranslationModel(56, 50, "缺乏的"),
            new TranslationModel(57, 10, "comportement"),
            new TranslationModel(57, 20, "הִתנָהָגוּת"),
            new TranslationModel(57, 30, "манера держаться, поведение"),
            new TranslationModel(57, 40, "comportamento"),
            new TranslationModel(57, 50, "举止，品行"),
            new TranslationModel(58, 10, "déprimer"),
            new TranslationModel(58, 20, "לְדַכֵּא"),
            new TranslationModel(58, 30, "приводить в уныние"),
            new TranslationModel(58, 40, "deprimere"),
            new TranslationModel(58, 50, "使沮丧"),
            new TranslationModel(59, 10, "retenir"),
            new TranslationModel(59, 20, "לְעַכֵּב"),
            new TranslationModel(59, 30, "задерживать"),
            new TranslationModel(59, 40, "trattenere"),
            new TranslationModel(59, 50, "留住"),
            new TranslationModel(60, 10, "diarrhée"),
            new TranslationModel(60, 20, "שִׁלשׁוּל"),
            new TranslationModel(60, 30, "диарея"),
            new TranslationModel(60, 40, "diarrea"),
            new TranslationModel(60, 50, "腹泻"),
            new TranslationModel(61, 10, "vacarme"),
            new TranslationModel(61, 20, "רָעַש"),
            new TranslationModel(61, 30, "грохот"),
            new TranslationModel(61, 40, "chiasso, frastuono"),
            new TranslationModel(61, 50, "喧声"),
            new TranslationModel(62, 10, "(re)nier"),
            new TranslationModel(62, 20, "לְהַכּחִיש"),
            new TranslationModel(62, 30, "отрекаться, отказываться"),
            new TranslationModel(62, 40, "rinnegare, disconoscere"),
            new TranslationModel(62, 50, "否认"),
            new TranslationModel(63, 10, "malhonnête"),
            new TranslationModel(63, 20, "לֹא יָשַר"),
            new TranslationModel(63, 30, "нечестный"),
            new TranslationModel(63, 40, "disonesto"),
            new TranslationModel(63, 50, "不诚实的"),
            new TranslationModel(64, 10, "discrédit"),
            new TranslationModel(64, 20, "שֵׁם רָע"),
            new TranslationModel(64, 30, "дурная слава"),
            new TranslationModel(64, 40, "discredito"),
            new TranslationModel(64, 50, "声名狼藉"),
            new TranslationModel(65, 10, "détourner"),
            new TranslationModel(65, 20, "לְהָטוֹת"),
            new TranslationModel(65, 30, "отводить в сторону"),
            new TranslationModel(65, 40, "deviare"),
            new TranslationModel(65, 50, "使转向"),
            new TranslationModel(66, 10, "dominant"),
            new TranslationModel(66, 20, "שוֹלֶט"),
            new TranslationModel(66, 30, "преобладающий"),
            new TranslationModel(66, 40, "dominante"),
            new TranslationModel(66, 50, "占优势的，支配的"),
            new TranslationModel(67, 10, "drainer"),
            new TranslationModel(67, 20, "לְנָקֵז"),
            new TranslationModel(67, 30, "осушать"),
            new TranslationModel(67, 40, "prosciugare"),
            new TranslationModel(67, 50, "排去（水等液体）"),
            new TranslationModel(68, 10, "dupe"),
            new TranslationModel(68, 20, "פֶּתִי"),
            new TranslationModel(68, 30, "простофиля"),
            new TranslationModel(68, 40, "vittima"),
            new TranslationModel(68, 50, "受骗的人，上当者"),
            new TranslationModel(69, 10, "anguille"),
            new TranslationModel(69, 20, "צְלוֹפֳח"),
            new TranslationModel(69, 30, "угорь"),
            new TranslationModel(69, 40, "anguilla"),
            new TranslationModel(69, 50, "鳗鲡"),
            new TranslationModel(70, 10, "braise"),
            new TranslationModel(70, 20, "גָחֶלֶת"),
            new TranslationModel(70, 30, "последние тлеющие угольки"),
            new TranslationModel(70, 40, "brace"),
            new TranslationModel(70, 50, "余火，余烬"),
            new TranslationModel(71, 10, "promulguer"),
            new TranslationModel(71, 20, "לְחוֹקֵק"),
            new TranslationModel(71, 30, "вводить в действие (закон)"),
            new TranslationModel(71, 40, "convertire in legge, promulgare; ordinare"),
            new TranslationModel(71, 50, "制定法律"),
            new TranslationModel(72, 10, "hostilité"),
            new TranslationModel(72, 20, "אֵיבָה"),
            new TranslationModel(72, 30, "вражда"),
            new TranslationModel(72, 40, "inimicizia"),
            new TranslationModel(72, 50, "敌意，仇恨"),
            new TranslationModel(73, 10, "énumérer"),
            new TranslationModel(73, 20, "לִמנוֹת"),
            new TranslationModel(73, 30, "перечислять"),
            new TranslationModel(73, 40, "enumerare"),
            new TranslationModel(73, 50, "枚举，列举"),
            new TranslationModel(74, 10, "droit, dressé"),
            new TranslationModel(74, 20, "זָקוּף"),
            new TranslationModel(74, 30, "прямой"),
            new TranslationModel(74, 40, "eretto"),
            new TranslationModel(74, 50, "坚立的"),
            new TranslationModel(75, 10, "étiquette"),
            new TranslationModel(75, 20, "כְּלָלֵי נִימוּס"),
            new TranslationModel(75, 30, "этикет; (профессиональная) этика"),
            new TranslationModel(75, 40, "etichetta, etica professionale"),
            new TranslationModel(75, 50, "礼节，成规"),
            new TranslationModel(76, 10, "exemple"),
            new TranslationModel(76, 20, "דוּגמָה"),
            new TranslationModel(76, 30, "образец"),
            new TranslationModel(76, 40, "esempio, campione"),
            new TranslationModel(76, 50, "样本"),
            new TranslationModel(77, 10, "disparu"),
            new TranslationModel(77, 20, "נִכחַד"),
            new TranslationModel(77, 30, "вымерший"),
            new TranslationModel(77, 40, "estinto"),
            new TranslationModel(77, 50, "绝种的，灭绝的"),
            new TranslationModel(78, 10, "faculté"),
            new TranslationModel(78, 20, "כּוֹשֶר"),
            new TranslationModel(78, 30, "способность"),
            new TranslationModel(78, 40, "facoltà"),
            new TranslationModel(78, 50, "能力"),
            new TranslationModel(79, 10, "ferme"),
            new TranslationModel(79, 20, "חַווָה"),
            new TranslationModel(79, 30, "ферма"),
            new TranslationModel(79, 40, "fattoria"),
            new TranslationModel(79, 50, "农场"),
            new TranslationModel(80, 10, "nourrir"),
            new TranslationModel(80, 20, "לְהַאֲכִיל"),
            new TranslationModel(80, 30, "кормить"),
            new TranslationModel(80, 40, "dar da mangiare, nutrire"),
            new TranslationModel(80, 50, "喂养"),
            new TranslationModel(81, 10, "filtre"),
            new TranslationModel(81, 20, "מַסנֵן"),
            new TranslationModel(81, 30, "фильтр"),
            new TranslationModel(81, 40, "filtro"),
            new TranslationModel(81, 50, "过滤器"),
            new TranslationModel(82, 10, "flamboyant"),
            new TranslationModel(82, 20, "סַסגוֹנִי"),
            new TranslationModel(82, 30, "броский"),
            new TranslationModel(82, 40, "sgargiante"),
            new TranslationModel(82, 50, "艳丽的"),
            new TranslationModel(83, 10, "flirter"),
            new TranslationModel(83, 20, "לְחָזֵר בִּקלִילוּת"),
            new TranslationModel(83, 30, "флиртовать"),
            new TranslationModel(83, 40, "amoreggiare, flirtare"),
            new TranslationModel(83, 50, "调情"),
            new TranslationModel(84, 10, "FM"),
            new TranslationModel(84, 20, "אפנון תדר, אף-אם"),
            new TranslationModel(84, 30, "частотная модуляция"),
            new TranslationModel(84, 40, "FM"),
            new TranslationModel(84, 50, "调频(缩写式)"),
            new TranslationModel(85, 10, "abandonner"),
            new TranslationModel(85, 20, "לִנטוֹש"),
            new TranslationModel(85, 30, "покидать"),
            new TranslationModel(85, 40, "abbandonare"),
            new TranslationModel(85, 50, "抛弃"),
            new TranslationModel(86, 10, "fou d'inquiétude"),
            new TranslationModel(86, 20, "שֶׁל טֵירוּף"),
            new TranslationModel(86, 30, "обезумевший"),
            new TranslationModel(86, 40, "furibondo"),
            new TranslationModel(86, 50, "焦虑不安的"),
            new TranslationModel(87, 10, "froncer les sourcils"),
            new TranslationModel(87, 20, "לְקַמֵט אֶת הַמֵצָח"),
            new TranslationModel(87, 30, "хмуриться"),
            new TranslationModel(87, 40, "accigliarsi, aggrottare le ciglia/sopracciglia"),
            new TranslationModel(87, 50, "皱眉"),
            new TranslationModel(88, 10, "fusionner"),
            new TranslationModel(88, 20, "לְהַתִּיך"),
            new TranslationModel(88, 30, "сплавлять(ся)"),
            new TranslationModel(88, 40, "fondere"),
            new TranslationModel(88, 50, "熔合"),
            new TranslationModel(89, 10, "empoté"),
            new TranslationModel(89, 20, "מְגוּשָׁם"),
            new TranslationModel(89, 30, "неуклюжий"),
            new TranslationModel(89, 40, "goffo"),
            new TranslationModel(89, 50, "笨拙的"),
            new TranslationModel(90, 10, "gentillesse, distinction"),
            new TranslationModel(90, 20, "נימוסיות"),
            new TranslationModel(90, 30, "аристократические замашки"),
            new TranslationModel(90, 40, "gentilezza, raffinatezza"),
            new TranslationModel(90, 50, "假斯文，文雅，有教养"),
            new TranslationModel(91, 10, "brillant"),
            new TranslationModel(91, 20, "בָּרָק"),
            new TranslationModel(91, 30, "блеск"),
            new TranslationModel(91, 40, "lucentezza; brillante"),
            new TranslationModel(91, 50, "光泽"),
            new TranslationModel(92, 10, "gong"),
            new TranslationModel(92, 20, "גוֹנג"),
            new TranslationModel(92, 30, "гонг"),
            new TranslationModel(92, 40, "gong"),
            new TranslationModel(92, 50, "铜锣"),
            new TranslationModel(93, 10, "brouter"),
            new TranslationModel(93, 20, "לִרעוֹת"),
            new TranslationModel(93, 30, "пастись"),
            new TranslationModel(93, 40, "pascolare, brucare"),
            new TranslationModel(93, 50, "（让动物）吃草，放牧"),
            new TranslationModel(94, 10, "sol, terre"),
            new TranslationModel(94, 20, "קַרקָע, אֲדָמָה, הָאָרֶץ"),
            new TranslationModel(94, 30, "земля"),
            new TranslationModel(94, 40, "terra, suolo"),
            new TranslationModel(94, 50, "地面"),
            new TranslationModel(95, 10, "engloutir"),
            new TranslationModel(95, 20, "לִגמוֹע"),
            new TranslationModel(95, 30, "проглатывать"),
            new TranslationModel(95, 40, "inghiottire"),
            new TranslationModel(95, 50, "狼吞虎咽"),
            new TranslationModel(96, 10, "poil"),
            new TranslationModel(96, 20, "שֵׂיעָר"),
            new TranslationModel(96, 30, "волосок; шерсть"),
            new TranslationModel(96, 40, "pelo"),
            new TranslationModel(96, 50, "毛发"),
            new TranslationModel(97, 10, "port"),
            new TranslationModel(97, 20, "נָמָל"),
            new TranslationModel(97, 30, "порт"),
            new TranslationModel(97, 40, "porto"),
            new TranslationModel(97, 50, "港口"),
            new TranslationModel(98, 10, "héritier/-ière"),
            new TranslationModel(98, 20, "יוֹרֵש"),
            new TranslationModel(98, 30, "наследник"),
            new TranslationModel(98, 40, "erede; ereditiera"),
            new TranslationModel(98, 50, "继承人"),
            new TranslationModel(99, 10, "hanche"),
            new TranslationModel(99, 20, "מִפרַק הַיָרֵך"),
            new TranslationModel(99, 30, "бедро"),
            new TranslationModel(99, 40, "anca"),
            new TranslationModel(99, 50, "髋关节"),
            new TranslationModel(100, 10, "horreur"),
            new TranslationModel(100, 20, "אֵימָה"),
            new TranslationModel(100, 30, "отвращение;ужас"),
            new TranslationModel(100, 40, "orrore"),
            new TranslationModel(100, 50, "极端厌恶"),
            new TranslationModel(101, 10, "humain"),
            new TranslationModel(101, 20, "אֶנוֹשִׁי"),
            new TranslationModel(101, 30, "гуманный"),
            new TranslationModel(101, 40, "umano"),
            new TranslationModel(101, 50, "仁慈的，人道的"),
            new TranslationModel(102, 10, "locution idiomatique"),
            new TranslationModel(102, 20, "צֵירוּף מִילִים"),
            new TranslationModel(102, 30, "идиома"),
            new TranslationModel(102, 40, "espressione idiomatica"),
            new TranslationModel(102, 50, "成语"),
            new TranslationModel(103, 10, "immense"),
            new TranslationModel(103, 20, "עֲצוּם"),
            new TranslationModel(103, 30, "огромный"),
            new TranslationModel(103, 40, "immenso"),
            new TranslationModel(103, 50, "巨大的"),
            new TranslationModel(104, 10, "implorer"),
            new TranslationModel(104, 20, "לְהִתחַנֵן"),
            new TranslationModel(104, 30, "умолять"),
            new TranslationModel(104, 40, "implorare"),
            new TranslationModel(104, 50, "恳求，乞求"),
            new TranslationModel(105, 10, "inattentif"),
            new TranslationModel(105, 20, "שֶׁאֵינוֹ שָׂם לֵב"),
            new TranslationModel(105, 30, "невнимательный"),
            new TranslationModel(105, 40, "disattento"),
            new TranslationModel(105, 50, "不注意的"),
            new TranslationModel(106, 10, "inconsidéré, sans égards"),
            new TranslationModel(106, 20, "לא מִתחַשֵב"),
            new TranslationModel(106, 30, "опрометчивый"),
            new TranslationModel(106, 40, "sconsiderato"),
            new TranslationModel(106, 50, "考虑不周的，不替别人着想的"),
            new TranslationModel(107, 10, "souffrant"),
            new TranslationModel(107, 20, "לא בְקַו הַבְּרִיאות"),
            new TranslationModel(107, 30, "(немного) нездоровый"),
            new TranslationModel(107, 40, "indisposto"),
            new TranslationModel(107, 50, "有小病的，不舒服的"),
            new TranslationModel(108, 10, "(s')infiltrer (dans)"),
            new TranslationModel(108, 20, "לְהִסתַּנֵן"),
            new TranslationModel(108, 30, "проникать в тыл противника"),
            new TranslationModel(108, 40, "infiltrarsi in"),
            new TranslationModel(108, 50, "渗透"),
            new TranslationModel(109, 10, "encre"),
            new TranslationModel(109, 20, "דְיוֹ"),
            new TranslationModel(109, 30, "чернила"),
            new TranslationModel(109, 40, "inchiostro"),
            new TranslationModel(109, 50, "墨水"),
            new TranslationModel(110, 10, "perspicacité"),
            new TranslationModel(110, 20, "הֲבָנָה מַעֲמִיקָה"),
            new TranslationModel(110, 30, "проницательность"),
            new TranslationModel(110, 40, "perspicacia"),
            new TranslationModel(110, 50, "洞悉，洞察力"),
            new TranslationModel(111, 10, "intervalle"),
            new TranslationModel(111, 20, "הַפסָקָה"),
            new TranslationModel(111, 30, "интервал"),
            new TranslationModel(111, 40, "intervallo"),
            new TranslationModel(111, 50, "间隔"),
            new TranslationModel(112, 10, "invisible"),
            new TranslationModel(112, 20, "בִּלתִי נִראֶה"),
            new TranslationModel(112, 30, "невидимый"),
            new TranslationModel(112, 40, "invisibile"),
            new TranslationModel(112, 50, "看不见的"),
            new TranslationModel(113, 10, "-âtre"),
            new TranslationModel(113, 20, "בקרוב"),
            new TranslationModel(113, 30, "-оватый (передаёт значение слабой выраженности признака)"),
            new TranslationModel(113, 40, "suff. di origine anglosassone con valore di approssimazione"),
            new TranslationModel(113, 50, "带…的；稍…的"),
            new TranslationModel(114, 10, "déchiqueté"),
            new TranslationModel(114, 20, "מְשוּנָן"),
            new TranslationModel(114, 30, "с зазубринами"),
            new TranslationModel(114, 40, "puntuto, frastagliato"),
            new TranslationModel(114, 50, "锯齿状的"),
            new TranslationModel(115, 10, "moquerie"),
            new TranslationModel(115, 20, "עֲקִיצָה פּוֹגַעַת"),
            new TranslationModel(115, 30, "насмешка"),
            new TranslationModel(115, 40, "beffa, derisione"),
            new TranslationModel(115, 50, "嘲弄"),
            new TranslationModel(116, 10, "cruche, carafe"),
            new TranslationModel(116, 20, "כָּד"),
            new TranslationModel(116, 30, "кувшин"),
            new TranslationModel(116, 40, "brocca, caraffa"),
            new TranslationModel(116, 50, "（有柄有嘴的）壶"),
            new TranslationModel(117, 10, "karaoké"),
            new TranslationModel(117, 20, "קריוקי"),
            new TranslationModel(117, 30, "караоке"),
            new TranslationModel(117, 40, "karaoke"),
            new TranslationModel(117, 50, "卡拉OK"),
            new TranslationModel(118, 10, "cinétique"),
            new TranslationModel(118, 20, "קִינֶטִי"),
            new TranslationModel(118, 30, "кинетический"),
            new TranslationModel(118, 40, "cinetico"),
            new TranslationModel(118, 50, "运动的"),
            new TranslationModel(119, 10, "(se) languir"),
            new TranslationModel(119, 20, "לְהֵיחָלֵש"),
            new TranslationModel(119, 30, "слабеть, чахнуть"),
            new TranslationModel(119, 40, "languire"),
            new TranslationModel(119, 50, "变得越来越衰弱，凋萎"),
            new TranslationModel(120, 10, "grand livre"),
            new TranslationModel(120, 20, "סֵפֶר חֶשבּוֹנוֹת"),
            new TranslationModel(120, 30, "гроссбух"),
            new TranslationModel(120, 40, "libro mastro"),
            new TranslationModel(120, 50, "分类帐"),
            new TranslationModel(121, 10, "rythme, cadence"),
            new TranslationModel(121, 20, "שִׁיר קִצבִּי"),
            new TranslationModel(121, 30, "подчёркнутый ритм"),
            new TranslationModel(121, 40, "(ritmo vivace)"),
            new TranslationModel(121, 50, "轻快旋律，轻快活泼的调子"),
            new TranslationModel(122, 10, "mèche"),
            new TranslationModel(122, 20, "תַּלתַּל"),
            new TranslationModel(122, 30, "локон"),
            new TranslationModel(122, 40, "ciocca"),
            new TranslationModel(122, 50, "一绺头发"),
            new TranslationModel(123, 10, "se prélasser"),
            new TranslationModel(123, 20, "לַשֶׁבֶת/לִשכַּב בְּנוֹחוּת"),
            new TranslationModel(123, 30, "лежать в ленивой позе"),
            new TranslationModel(123, 40, "stare disteso/sdraiato"),
            new TranslationModel(123, 50, "懒洋洋地躺卧"),
            new TranslationModel(124, 10, "succulent"),
            new TranslationModel(124, 20, "טָעִים, מָתוֹק"),
            new TranslationModel(124, 30, "сладкий и сочный"),
            new TranslationModel(124, 40, "succulento"),
            new TranslationModel(124, 50, "甘美的"),
            new TranslationModel(125, 10, "magnanime"),
            new TranslationModel(125, 20, "נָדִיב"),
            new TranslationModel(125, 30, "великодушный"),
            new TranslationModel(125, 40, "magnanimo"),
            new TranslationModel(125, 50, "宽宏大量的"),
            new TranslationModel(126, 10, "homme"),
            new TranslationModel(126, 20, "גֶבֶר, אִיש"),
            new TranslationModel(126, 30, "мужчина"),
            new TranslationModel(126, 40, "uomo"),
            new TranslationModel(126, 50, "男子"),
            new TranslationModel(127, 10, "marijuana"),
            new TranslationModel(127, 20, "מַרִיחוּאָנָה"),
            new TranslationModel(127, 30, "марихуана"),
            new TranslationModel(127, 40, "marijuana"),
            new TranslationModel(127, 50, "大麻"),
            new TranslationModel(128, 10, "maigre"),
            new TranslationModel(128, 20, "דַל"),
            new TranslationModel(128, 30, "скудный"),
            new TranslationModel(128, 40, "misero"),
            new TranslationModel(128, 50, "贫弱的，贫乏的"),
            new TranslationModel(129, 10, "mélanine"),
            new TranslationModel(129, 20, "מלנין"),
            new TranslationModel(129, 30, "меланин"),
            new TranslationModel(129, 40, "melanina"),
            new TranslationModel(129, 50, "黑色素"),
            new TranslationModel(130, 10, "mérite"),
            new TranslationModel(130, 20, "עֵרֶך"),
            new TranslationModel(130, 30, "заслуга"),
            new TranslationModel(130, 40, "merito"),
            new TranslationModel(130, 50, "功绩"),
            new TranslationModel(131, 10, "méfait, mauvais coup"),
            new TranslationModel(131, 20, "תַעֲלוּלִים, שוֹבבוּת"),
            new TranslationModel(131, 30, "шалость"),
            new TranslationModel(131, 40, "guaio, birichinata"),
            new TranslationModel(131, 50, "捣蛋"),
            new TranslationModel(132, 10, "morbide"),
            new TranslationModel(132, 20, "חוֹלָנִי"),
            new TranslationModel(132, 30, "болезненный, нездоровый"),
            new TranslationModel(132, 40, "morboso"),
            new TranslationModel(132, 50, "病态的"),
            new TranslationModel(133, 10, "(de) montagne"),
            new TranslationModel(133, 20, "הַר"),
            new TranslationModel(133, 30, "гора"),
            new TranslationModel(133, 40, "montagna; di montagna"),
            new TranslationModel(133, 50, "山"),
            new TranslationModel(134, 10, "multiplier"),
            new TranslationModel(134, 20, "לְהַכפִּיל"),
            new TranslationModel(134, 30, "умножать, множить"),
            new TranslationModel(134, 40, "moltiplicare"),
            new TranslationModel(134, 50, "乘"),
            new TranslationModel(135, 10, "myopie"),
            new TranslationModel(135, 20, "קוֹצֶר רְאִייָה"),
            new TranslationModel(135, 30, "близорукость"),
            new TranslationModel(135, 40, "miopia"),
            new TranslationModel(135, 50, "近视"),
            new TranslationModel(136, 10, "sans arrêt, direct"),
            new TranslationModel(136, 20, "ללא הַפסָקָה"),
            new TranslationModel(136, 30, "безостановочный"),
            new TranslationModel(136, 40, "senza fermate, non stop, ininterrotto"),
            new TranslationModel(136, 50, "中途不停的，直达的"),
            new TranslationModel(137, 10, "près de"),
            new TranslationModel(137, 20, "קרוב"),
            new TranslationModel(137, 30, "близко, недалеко, около"),
            new TranslationModel(137, 40, "nr"),
            new TranslationModel(137, 50, "在...附近(缩写式)"),
            new TranslationModel(138, 10, "obélisque"),
            new TranslationModel(138, 20, "אובליסק"),
            new TranslationModel(138, 30, "обелиск"),
            new TranslationModel(138, 40, "obelisco"),
            new TranslationModel(138, 50, "方尖塔, 方尖碑"),
            new TranslationModel(139, 10, "omnivore"),
            new TranslationModel(139, 20, "אוכל כל"),
            new TranslationModel(139, 30, "всеядное существо"),
            new TranslationModel(139, 40, "onnivoro"),
            new TranslationModel(139, 50, "杂食动物, 杂食的人"),
            new TranslationModel(140, 10, "optimiser"),
            new TranslationModel(140, 20, "לייעל, למטב"),
            new TranslationModel(140, 30, "оптимизировать"),
            new TranslationModel(140, 40, "ottimizzare"),
            new TranslationModel(140, 50, "使最优化, 使最有效地进行"),
            new TranslationModel(141, 10, "osmose"),
            new TranslationModel(141, 20, "אוסמוזה"),
            new TranslationModel(141, 30, "осмос"),
            new TranslationModel(141, 40, "osmosi"),
            new TranslationModel(141, 50, "渗透(作用)"),
            new TranslationModel(142, 10, "franchement"),
            new TranslationModel(142, 20, "בְּגָלוּי"),
            new TranslationModel(142, 30, "открыто, прямо"),
            new TranslationModel(142, 40, "apertamente"),
            new TranslationModel(142, 50, "直率地"),
            new TranslationModel(143, 10, "(se) chevaucher"),
            new TranslationModel(143, 20, "לַחפוֹף"),
            new TranslationModel(143, 30, "перекрывать"),
            new TranslationModel(143, 40, "sovrapporre, sovrapporsi"),
            new TranslationModel(143, 50, "叠盖"),
            new TranslationModel(144, 10, "paroxysme, crise"),
            new TranslationModel(144, 20, "הֶתקֵף פִּתאוֹמִי"),
            new TranslationModel(144, 30, "приступ"),
            new TranslationModel(144, 40, "parossismo"),
            new TranslationModel(144, 50, "突然发作"),
            new TranslationModel(145, 10, "brevet (d'invention) (noun), breveté (adjective)"),
            new TranslationModel(145, 20, "רִישָׁיוֹן פָּטֶנְט"),
            new TranslationModel(145, 30, "патент"),
            new TranslationModel(145, 40, "brevetto"),
            new TranslationModel(145, 50, "专利，专利权"),
            new TranslationModel(146, 10, "s'infiltrer"),
            new TranslationModel(146, 20, "לַחֲדוֹר"),
            new TranslationModel(146, 30, "пропитывать;просачиваться"),
            new TranslationModel(146, 40, "penetrare, diffondersi"),
            new TranslationModel(146, 50, "渗入"),
            new TranslationModel(147, 10, "phagocyte"),
            new TranslationModel(147, 20, "פגוציט"),
            new TranslationModel(147, 30, "фагоцит"),
            new TranslationModel(147, 40, "fagocita"),
            new TranslationModel(147, 50, "吞噬细胞"),
            new TranslationModel(148, 10, "physique"),
            new TranslationModel(148, 20, "מִבנֶה גוּף"),
            new TranslationModel(148, 30, "телосложение"),
            new TranslationModel(148, 40, "fisico"),
            new TranslationModel(148, 50, "体格，体形"),
            new TranslationModel(149, 10, "bouton"),
            new TranslationModel(149, 20, "פִּצעוֹן"),
            new TranslationModel(149, 30, "прыщ(ик)"),
            new TranslationModel(149, 40, "brufolo"),
            new TranslationModel(149, 50, "脓疮"),
            new TranslationModel(150, 10, "crépitement"),
            new TranslationModel(150, 20, "נְקִישוֹת מְהִירוֹת ותכוּפוֹת"),
            new TranslationModel(150, 30, "лёгкое постукивание"),
            new TranslationModel(150, 40, "picchiettio"),
            new TranslationModel(150, 50, "劈劈啪啪声"),
            new TranslationModel(151, 10, "(de) platine"),
            new TranslationModel(151, 20, "פְּלָטִינָה"),
            new TranslationModel(151, 30, "платина"),
            new TranslationModel(151, 40, "platino; di platino"),
            new TranslationModel(151, 50, "铂，白金"),
            new TranslationModel(152, 10, "(en) porcelaine"),
            new TranslationModel(152, 20, "חַרסִינָה"),
            new TranslationModel(152, 30, "фарфор"),
            new TranslationModel(152, 40, "porcellana; di porcellana"),
            new TranslationModel(152, 50, "瓷器"),
            new TranslationModel(153, 10, "postérieur"),
            new TranslationModel(153, 20, "אֲחוֹרִי"),
            new TranslationModel(153, 30, "задний"),
            new TranslationModel(153, 40, "posteriore"),
            new TranslationModel(153, 50, "后来的，（位置上）后面的"),
            new TranslationModel(154, 10, "relations publiques"),
            new TranslationModel(154, 20, "יַחצָנוּת"),
            new TranslationModel(154, 30, "связи с общественностью"),
            new TranslationModel(154, 40, "pubbliche relazioni"),
            new TranslationModel(154, 50, "公共关系（缩写式）"),
            new TranslationModel(155, 10, "enceinte"),
            new TranslationModel(155, 20, "בְּהֵיריוֹן"),
            new TranslationModel(155, 30, "беременная"),
            new TranslationModel(155, 40, "incinta"),
            new TranslationModel(155, 50, "怀孕的"),
            new TranslationModel(156, 10, "empêcher (de)"),
            new TranslationModel(156, 20, "לִמנוֹעַ"),
            new TranslationModel(156, 30, "предотвращать; препятствовать"),
            new TranslationModel(156, 40, "impedire"),
            new TranslationModel(156, 50, "阻止，防止"),
            new TranslationModel(157, 10, "probable"),
            new TranslationModel(157, 20, "מִסתַבֵּר"),
            new TranslationModel(157, 30, "вероятный"),
            new TranslationModel(157, 40, "probabile"),
            new TranslationModel(157, 50, "很可能的"),
            new TranslationModel(158, 10, "(couché) sur le ventre"),
            new TranslationModel(158, 20, "שָכוּב עַל בִּטנוֹ"),
            new TranslationModel(158, 30, "лежащий ничком"),
            new TranslationModel(158, 40, "prono"),
            new TranslationModel(158, 50, "面向下的，俯卧的"),
            new TranslationModel(159, 10, "fournir"),
            new TranslationModel(159, 20, "לְסַפֵּק"),
            new TranslationModel(159, 30, "давать, снабжать"),
            new TranslationModel(159, 40, "fornire"),
            new TranslationModel(159, 50, "提供"),
            new TranslationModel(160, 10, "but, objet"),
            new TranslationModel(160, 20, "מַטָרָה"),
            new TranslationModel(160, 30, "цель"),
            new TranslationModel(160, 40, "scopo"),
            new TranslationModel(160, 50, "目的"),
            new TranslationModel(161, 10, "(de) qualité"),
            new TranslationModel(161, 20, "אֵיכוּת"),
            new TranslationModel(161, 30, "сорт; качество"),
            new TranslationModel(161, 40, "qualità; di qualità"),
            new TranslationModel(161, 50, "质量"),
            new TranslationModel(162, 10, "quitter, abandonner"),
            new TranslationModel(162, 20, "לַעֲזוֹב"),
            new TranslationModel(162, 30, "оставлять"),
            new TranslationModel(162, 40, "abbandonare, lasciare"),
            new TranslationModel(162, 50, "离开，停止，放弃，解除"),
            new TranslationModel(163, 10, "(de) viol"),
            new TranslationModel(163, 20, "אוֹנֶס"),
            new TranslationModel(163, 30, "изнасилование"),
            new TranslationModel(163, 40, "stupro"),
            new TranslationModel(163, 50, "强奸罪"),
            new TranslationModel(164, 10, "re-, ré-"),
            new TranslationModel(164, 20, "שוב, מחדש"),
            new TranslationModel(164, 30, "передаёт значение \"повторно\", \"заново\", \"ещё раз\""),
            new TranslationModel(164, 40, "ri-"),
            new TranslationModel(164, 50, "再；又"),
            new TranslationModel(165, 10, "réceptif"),
            new TranslationModel(165, 20, "פָּתוּחַ"),
            new TranslationModel(165, 30, "восприимчивый"),
            new TranslationModel(165, 40, "ricettivo"),
            new TranslationModel(165, 50, "有接受能力的，（对新的思想等）善于接受的"),
            new TranslationModel(166, 10, "se reproduire"),
            new TranslationModel(166, 20, "לְהִישָׁנוֹת"),
            new TranslationModel(166, 30, "повторяться;возвращаться"),
            new TranslationModel(166, 40, "ripresentarsi, ripetersi"),
            new TranslationModel(166, 50, "再次发生，复发"),
            new TranslationModel(167, 10, "ordures"),
            new TranslationModel(167, 20, "אַשפָּה"),
            new TranslationModel(167, 30, "мусор"),
            new TranslationModel(167, 40, "spazzatura, rifiuti*"),
            new TranslationModel(167, 50, "废物，垃圾"),
            new TranslationModel(168, 10, "soulagement"),
            new TranslationModel(168, 20, "הַקָלָה"),
            new TranslationModel(168, 30, "облегчение"),
            new TranslationModel(168, 40, "sollievo"),
            new TranslationModel(168, 50, "（痛苦的）减轻"),
            new TranslationModel(169, 10, "remplacer"),
            new TranslationModel(169, 20, "לְהַחֲלִיף"),
            new TranslationModel(169, 30, "заменять"),
            new TranslationModel(169, 40, "sostituire"),
            new TranslationModel(169, 50, "更换，替换"),
            new TranslationModel(170, 10, "ressource(s)"),
            new TranslationModel(170, 20, "מַשאָב"),
            new TranslationModel(170, 30, "возможность; средство"),
            new TranslationModel(170, 40, "risorsa"),
            new TranslationModel(170, 50, "物力财力对策，办法"),
            new TranslationModel(171, 10, "révéler"),
            new TranslationModel(171, 20, "לְגָלוֹת"),
            new TranslationModel(171, 30, "открывать; разоблачать"),
            new TranslationModel(171, 40, "rivelare"),
            new TranslationModel(171, 50, "泄露"),
            new TranslationModel(172, 10, "ribosome"),
            new TranslationModel(172, 20, "ריבוזום"),
            new TranslationModel(172, 30, "рибосома"),
            new TranslationModel(172, 40, "ribosoma"),
            new TranslationModel(172, 50, "核糖体；核糖核蛋白体"),
            new TranslationModel(173, 10, "route, routier"),
            new TranslationModel(173, 20, "כְּבִיש"),
            new TranslationModel(173, 30, "дорога; дорожный"),
            new TranslationModel(173, 40, "strada; stradale"),
            new TranslationModel(173, 50, "道路"),
            new TranslationModel(174, 10, "scandale"),
            new TranslationModel(174, 20, "שַׁעֲרוּרִייָה"),
            new TranslationModel(174, 30, "скандальное происшествие;безобразие"),
            new TranslationModel(174, 40, "scandalo"),
            new TranslationModel(174, 50, "丑闻"),
            new TranslationModel(175, 10, "mettre à"),
            new TranslationModel(175, 20, "לָשִׂים קֵץ"),
            new TranslationModel(175, 30, "положить конец"),
            new TranslationModel(175, 40, "far cessare; mandare a monte"),
            new TranslationModel(175, 50, "粉碎，戳穿"),
            new TranslationModel(176, 10, "bagarre"),
            new TranslationModel(176, 20, "תִּגרָה"),
            new TranslationModel(176, 30, "потасовка"),
            new TranslationModel(176, 40, "rissa"),
            new TranslationModel(176, 50, "混战，扭打"),
            new TranslationModel(177, 10, "voir"),
            new TranslationModel(177, 20, "לִראוֹת"),
            new TranslationModel(177, 30, "видеть"),
            new TranslationModel(177, 40, "vedere"),
            new TranslationModel(177, 50, "看见"),
            new TranslationModel(178, 10, "maître de soi"),
            new TranslationModel(178, 20, "מוֹשֵל בְּרוּחוֹ"),
            new TranslationModel(178, 30, "выдержанный, наделённый самообладанием"),
            new TranslationModel(178, 40, "padrone di sé"),
            new TranslationModel(178, 50, "沉着的"),
            new TranslationModel(179, 10, "sensibilité"),
            new TranslationModel(179, 20, "רְגִישוּת"),
            new TranslationModel(179, 30, "чувствительность, восприимчивость"),
            new TranslationModel(179, 40, "sensibilità"),
            new TranslationModel(179, 50, "识别力，敏感性"),
            new TranslationModel(180, 10, "part"),
            new TranslationModel(180, 20, "חֵלֶק"),
            new TranslationModel(180, 30, "часть, доля"),
            new TranslationModel(180, 40, "parte, porzione"),
            new TranslationModel(180, 50, "一份"),
            new TranslationModel(181, 10, "chemise"),
            new TranslationModel(181, 20, "חוּלצָה"),
            new TranslationModel(181, 30, "рубашка, сорочка"),
            new TranslationModel(181, 40, "camicia"),
            new TranslationModel(181, 50, "衬衫"),
            new TranslationModel(182, 10, "(faire) mijoter"),
            new TranslationModel(182, 20, "לְאדוֹת"),
            new TranslationModel(182, 30, "кипеть, кипятить на медленном огне"),
            new TranslationModel(182, 40, "bollire lentamente"),
            new TranslationModel(182, 50, "文火煨煮，慢煮"),
            new TranslationModel(183, 10, "déraper"),
            new TranslationModel(183, 20, "לְהַחֲלִיק"),
            new TranslationModel(183, 30, "заносить, пойти юзом"),
            new TranslationModel(183, 40, "sbandare, slittare"),
            new TranslationModel(183, 50, "打滑，滑向一侧"),
            new TranslationModel(184, 10, "déraper"),
            new TranslationModel(184, 20, "לְהִסתוֹבֵב"),
            new TranslationModel(184, 30, "круто поворачивать(ся)"),
            new TranslationModel(184, 40, "sbandare"),
            new TranslationModel(184, 50, "旋转"),
            new TranslationModel(185, 10, "casser, briser"),
            new TranslationModel(185, 20, "לְנַפֵּץ"),
            new TranslationModel(185, 30, "разбить(ся) вдребезги"),
            new TranslationModel(185, 40, "frantumare, fracassare"),
            new TranslationModel(185, 50, "打碎，毁坏"),
            new TranslationModel(186, 10, "ronfler"),
            new TranslationModel(186, 20, "לִנחוֹר"),
            new TranslationModel(186, 30, "храпеть"),
            new TranslationModel(186, 40, "russare"),
            new TranslationModel(186, 50, "打鼾"),
            new TranslationModel(187, 10, "grave"),
            new TranslationModel(187, 20, "קוֹדֵר"),
            new TranslationModel(187, 30, "серьёзный"),
            new TranslationModel(187, 40, "serio"),
            new TranslationModel(187, 50, "严肃的"),
            new TranslationModel(188, 10, "soupe, potage"),
            new TranslationModel(188, 20, "מָרָק"),
            new TranslationModel(188, 30, "суп"),
            new TranslationModel(188, 40, "zuppa, minestra"),
            new TranslationModel(188, 50, "汤"),
            new TranslationModel(189, 10, "tacheture, moucheture"),
            new TranslationModel(189, 20, "נְקוּדָה"),
            new TranslationModel(189, 30, "крапинка; пятнышко"),
            new TranslationModel(189, 40, "macchietta, puntino"),
            new TranslationModel(189, 50, "斑点"),
            new TranslationModel(190, 10, "se quereller/chamailler (à propos de)"),
            new TranslationModel(190, 20, "לַרִיב"),
            new TranslationModel(190, 30, "пререкаться; вздорить"),
            new TranslationModel(190, 40, "bisticciare"),
            new TranslationModel(190, 50, "（为琐事）争吵，争论"),
            new TranslationModel(191, 10, "atteint/frappé (par)"),
            new TranslationModel(191, 20, "מוּכֶּה"),
            new TranslationModel(191, 30, "поражённый"),
            new TranslationModel(191, 40, "colpito"),
            new TranslationModel(191, 50, "受...折磨的"),
            new TranslationModel(192, 10, "subvention"),
            new TranslationModel(192, 20, "תְּמִיכָה"),
            new TranslationModel(192, 30, "субсидия"),
            new TranslationModel(192, 40, "sussidio, sovvenzione"),
            new TranslationModel(192, 50, "政府津贴"),
            new TranslationModel(193, 10, "supersonique"),
            new TranslationModel(193, 20, "עַל-קוֹלִי"),
            new TranslationModel(193, 30, "сверхзвуковой"),
            new TranslationModel(193, 40, "supersonico"),
            new TranslationModel(193, 50, "超音速的"),
            new TranslationModel(194, 10, "se pavaner"),
            new TranslationModel(194, 20, "לְהֲלֵך בִּיהִירוּת"),
            new TranslationModel(194, 30, "расхаживать с важным видом"),
            new TranslationModel(194, 40, "pavoneggiarsi"),
            new TranslationModel(194, 50, "昂首阔步"),
            new TranslationModel(195, 10, "épée"),
            new TranslationModel(195, 20, "חֶרֶב"),
            new TranslationModel(195, 30, "меч; шпага"),
            new TranslationModel(195, 40, "spada"),
            new TranslationModel(195, 50, "剑，刀"),
            new TranslationModel(196, 10, "tactique"),
            new TranslationModel(196, 20, "טקטיקה"),
            new TranslationModel(196, 30, "тактика, план действий"),
            new TranslationModel(196, 40, "tattica"),
            new TranslationModel(196, 50, "实现政策的方法(或计划)"),
            new TranslationModel(197, 10, "technique"),
            new TranslationModel(197, 20, "טֶכנִי"),
            new TranslationModel(197, 30, "технический"),
            new TranslationModel(197, 40, "tecnico"),
            new TranslationModel(197, 50, "技术的"),
            new TranslationModel(198, 10, "tenter"),
            new TranslationModel(198, 20, "לְפָתוֹת"),
            new TranslationModel(198, 30, "соблазнять;прельщать"),
            new TranslationModel(198, 40, "tentare"),
            new TranslationModel(198, 50, "诱导，诱惑"),
            new TranslationModel(199, 10, "témoignage"),
            new TranslationModel(199, 20, "עֵדוּת"),
            new TranslationModel(199, 30, "свидетельские показания"),
            new TranslationModel(199, 40, "testimonianza"),
            new TranslationModel(199, 50, "证词"),
            new TranslationModel(200, 10, "voleur/-euse"),
            new TranslationModel(200, 20, "גַנָב"),
            new TranslationModel(200, 30, "вор"),
            new TranslationModel(200, 40, "ladro"),
            new TranslationModel(200, 50, "小偷"),
            new TranslationModel(201, 10, "foule"),
            new TranslationModel(201, 20, "הָמוֹן"),
            new TranslationModel(201, 30, "толпа"),
            new TranslationModel(201, 40, "folla"),
            new TranslationModel(201, 50, "人群"),
            new TranslationModel(202, 10, "pencher"),
            new TranslationModel(202, 20, "לְהַטוֹת"),
            new TranslationModel(202, 30, "наклонять(ся)"),
            new TranslationModel(202, 40, "inclinarsi"),
            new TranslationModel(202, 50, "使倾斜"),
            new TranslationModel(203, 10, "travailler dur"),
            new TranslationModel(203, 20, "לַעֲמוֹל"),
            new TranslationModel(203, 30, "усиленно трудиться"),
            new TranslationModel(203, 40, "faticare, sgobbare"),
            new TranslationModel(203, 50, "辛苦，苦干"),
            new TranslationModel(204, 10, "tourment"),
            new TranslationModel(204, 20, "יִיסוּרִים"),
            new TranslationModel(204, 30, "мучение"),
            new TranslationModel(204, 40, "tormento"),
            new TranslationModel(204, 50, "痛苦"),
            new TranslationModel(205, 10, "circulation, trafic"),
            new TranslationModel(205, 20, "תְנוּעָה, תַעֲבוּרָה"),
            new TranslationModel(205, 30, "движение, транспорт"),
            new TranslationModel(205, 40, "traffico"),
            new TranslationModel(205, 50, "交通"),
            new TranslationModel(206, 10, "émoi"),
            new TranslationModel(206, 20, "מְהוּמָה"),
            new TranslationModel(206, 30, "смятение"),
            new TranslationModel(206, 40, "tumulto"),
            new TranslationModel(206, 50, "混乱"),
            new TranslationModel(207, 10, "caractère"),
            new TranslationModel(207, 20, "אוֹתִיוֹת דְפוּס"),
            new TranslationModel(207, 30, "шрифт"),
            new TranslationModel(207, 40, "tipo, carattere"),
            new TranslationModel(207, 50, "（排版中的）铅字字号"),
            new TranslationModel(208, 10, "sans surveillance"),
            new TranslationModel(208, 20, "לְלא הַשגָחָה"),
            new TranslationModel(208, 30, "оставленный без присмотра"),
            new TranslationModel(208, 40, "solo, (senza sorveglianza)"),
            new TranslationModel(208, 50, "无人照顾的，无人陪伴的"),
            new TranslationModel(209, 10, "train d'atterrissage"),
            new TranslationModel(209, 20, "כַּן נְחִיתָה"),
            new TranslationModel(209, 30, "шасси"),
            new TranslationModel(209, 40, "carrello"),
            new TranslationModel(209, 50, "（飞机的）起落架，着陆装置"),
            new TranslationModel(210, 10, "déshabiller"),
            new TranslationModel(210, 20, "לְהַפשִיט"),
            new TranslationModel(210, 30, "раздевать"),
            new TranslationModel(210, 40, "spogliare, svestire"),
            new TranslationModel(210, 50, "（为某人）脱衣服"),
            new TranslationModel(211, 10, "discret"),
            new TranslationModel(211, 20, "שֶׁאֵינוֹ בּוֹלֵט לַעַיִן"),
            new TranslationModel(211, 30, "скромный"),
            new TranslationModel(211, 40, "discreto"),
            new TranslationModel(211, 50, "不引人注目的"),
            new TranslationModel(212, 10, "défaire la courroie de"),
            new TranslationModel(212, 20, "לִפתוֹחַ רְצוּעוֹת"),
            new TranslationModel(212, 30, "отстёгивать"),
            new TranslationModel(212, 40, "slacciare"),
            new TranslationModel(212, 50, "解开...的带子"),
            new TranslationModel(213, 10, "sur, à"),
            new TranslationModel(213, 20, "עַל-"),
            new TranslationModel(213, 30, "на; по"),
            new TranslationModel(213, 40, "su, a"),
            new TranslationModel(213, 50, "在......之上"),
            new TranslationModel(214, 10, "(de) gibier"),
            new TranslationModel(214, 20, "בְּשָר צְבִי"),
            new TranslationModel(214, 30, "оленина"),
            new TranslationModel(214, 40, "carne di cervo; di carne di cervo"),
            new TranslationModel(214, 50, "鹿肉"),
            new TranslationModel(215, 10, "(faire) vibrer"),
            new TranslationModel(215, 20, "לִרעוֹד"),
            new TranslationModel(215, 30, "вибрировать"),
            new TranslationModel(215, 40, "vibrare"),
            new TranslationModel(215, 50, "（使）振动"),
            new TranslationModel(216, 10, "visa"),
            new TranslationModel(216, 20, "אַשרָה, וִיזָה"),
            new TranslationModel(216, 30, "виза"),
            new TranslationModel(216, 40, "visto"),
            new TranslationModel(216, 50, "签证"),
            new TranslationModel(217, 10, "vulgaire"),
            new TranslationModel(217, 20, "גַס"),
            new TranslationModel(217, 30, "вульгарный"),
            new TranslationModel(217, 40, "volgare"),
            new TranslationModel(217, 50, "粗陋的，粗俗的，庸俗的"),
            new TranslationModel(218, 10, "gratuit"),
            new TranslationModel(218, 20, "זְדוֹנִי"),
            new TranslationModel(218, 30, "бессмысленный"),
            new TranslationModel(218, 40, "gratuito, arbitrario"),
            new TranslationModel(218, 50, "无理的"),
            new TranslationModel(219, 10, "fatigué"),
            new TranslationModel(219, 20, "עָיֵיף"),
            new TranslationModel(219, 30, "усталый"),
            new TranslationModel(219, 40, "stanco"),
            new TranslationModel(219, 50, "疲倦的"),
            new TranslationModel(220, 10, "quand"),
            new TranslationModel(220, 20, "מָתַי"),
            new TranslationModel(220, 30, "когда"),
            new TranslationModel(220, 40, "quando"),
            new TranslationModel(220, 50, "何时"),
            new TranslationModel(221, 10, "énorme"),
            new TranslationModel(221, 20, "עָצוּם"),
            new TranslationModel(221, 30, "огромный; чудовищный"),
            new TranslationModel(221, 40, "colossale"),
            new TranslationModel(221, 50, "巨大的，庞大的"),
            new TranslationModel(222, 10, "vanner"),
            new TranslationModel(222, 20, "לְנַפּוֹת"),
            new TranslationModel(222, 30, "отвеивать"),
            new TranslationModel(222, 40, "spulare"),
            new TranslationModel(222, 50, "扬（谷物）"),
            new TranslationModel(223, 10, "monde"),
            new TranslationModel(223, 20, "עוֹלָם"),
            new TranslationModel(223, 30, "земной шар"),
            new TranslationModel(223, 40, "mondo"),
            new TranslationModel(223, 50, "世界"),
            new TranslationModel(224, 10, "hier"),
            new TranslationModel(224, 20, "אֶתְמוֹל"),
            new TranslationModel(224, 30, "вчера"),
            new TranslationModel(224, 40, "ieri"),
            new TranslationModel(224, 50, "昨天"),
            new TranslationModel(225, 10, "zone"),
            new TranslationModel(225, 20, "אֵיזוֹר"),
            new TranslationModel(225, 30, "зона"),
            new TranslationModel(225, 40, "zona"),
            new TranslationModel(225, 50, "地区")
    };

    private static final LocaleModel[] locales = {
            new LocaleModel(10, "French", 1, 1),
            new LocaleModel(20, "Hebrew", 1, 1),
            new LocaleModel(30, "Russian", 1, 1),
            new LocaleModel(40, "Italian", 1, 1),
            new LocaleModel(50, "Chinese", 1, 1)
    };

}
